### ISSUE TITLE
Generating XML declaration

### ISSUE THREAD

**Issue by guidovandenheuvel** [edwindj/xmlwriter#3]
While testing I noticed that xmlwriter does not generate an XML declaration (i.e., `<?xml version="1.0" encoding="UTF-8"?>` ). If I do:

```
x <- list(a = list("test"))

# Obtain an XML string of x using xml2 library
xml <- xml2::as_xml_document(x)
xml2::write_xml(xml, "test.xml")
y1 <- paste(readLines("test.xml"), collapse = "\n")

# Do the same with xmlwriter
y2 <- xmlwriter::list_as_xml_string(x)

print(y1)
print(y2)

```
I get

```
> source("~/.active-rstudio-document")
[1] "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<a>test</a>"
[1] "<a>test</a>"

```
While it's easy enough to add the XML declaration myself, it might be better if xmlwriter were to include an XML declaration, just like the xml2 package does.

**Comment by edwindj** [comment]
Thanks for the suggestion and using the package!
 
I understand your use case, however xmlwriter supports both generating xml documents as wells as xml_fragments.
In the `xmlwriter` packages there is some (minimal) support for the two: `xml_doc` and `xml_fragment`. `xml_doc` is a special case of an `xml_fragment`, namely that it has exactly one rootnode.

The following is possible with the current version of `xmlwriter`


``` r
library(xmlwriter)
x <- list(a = list("test"))

x_doc <- x
class(x_doc) <- c("xml_doc", "xml_fragment")

x_doc |> as.character()
```

    ## [1] "<?xml version='1.0' encoding='UTF-8'?>\n <a>test</a>"

I am open to other suggestions: maybe the `list_as_xml_string` should gain an extra argument to write the xml declaration (or something like that)

**Comment by edwindj** [comment]
I added argument `use_prolog` to `list_as_xml_string`, so this is can used as follows:

```R
y2 <- xmlwriter::list_as_xml_string(x, use_prolog = TRUE)
```

**Comment by edwindj** [comment]
Closing it for now, do not hesitate to reopen when necessary
